### ISSUE TITLE
Popup statistics and notifications don't work

### ISSUE THREAD

**Issue by sideAgo** [Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice#7]
Hi
I thank you for the update because it solved the sensor unavailable problem.

However, the problem I had reported remains present, the markdown statistics page is empty unlike the other two (maintenance and settings).
The problem is due to the programming instructions under the content (set, if, for...). In fact, the others do not have these types of instructions and without this popup they work normally.

Using the card with the new changes also I noticed that the toggle to withdraw cloths no longer appears and notifications in general (app and alexa) do not work.

**Comment by marco-hacs** [comment]
You are not experiencing these problems with other people as well most likely the problem is due to your homaessistant instance (e.g. dublicated entities or incorrectly loaded files). What I would recommend is precisely to check for duplicate entities or alternatively delete everything, check that the entities have also been removed from ha..and reload the files.
